import { Opportunity, UserProfile } from '../types';

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'usr_001',
  name: 'Arsalan Qasim',
  email: 'arsalan.student@hec.edu.pk',
  major: 'Computer Science',
  academicLevel: 'Undergraduate',
  skills: ['React', 'TypeScript', 'Python', 'Tailwind CSS', 'Generative AI', 'Node.js', 'Git'],
  targetCategories: ['Hackathon', 'Scholarship', 'Internship', 'Grant'],
  preferredLocation: 'Remote',
  bio: 'Final year CS student passionate about building Agentic AI applications and full-stack web products.',
  emailNotifications: true
};

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp_001',
    title: 'Global AI Agents Hackathon 2026',
    organization: 'Lablab.ai & Google Cloud',
    category: 'Hackathon',
    deadline: '2026-08-15',
    location: 'Remote',
    stipendOrPrize: '$50,000 Total Prizes + Cloud Credits',
    techStackOrEligibility: ['Generative AI', 'Python', 'React', 'Gemini API', 'LangChain'],
    description: 'Build innovative multi-agent systems and autonomous AI applications using Gemini 1.5/2.0 APIs. Open to developers worldwide.',
    applyUrl: 'https://lablab.ai/event/global-ai-agents-hackathon-2026',
    featured: true,
    postedDate: '2026-07-20'
  },
  {
    id: 'opp_002',
    title: 'Fulbright Master\'s & PhD Scholarship 2026',
    organization: 'USEFP & HEC Pakistan',
    category: 'Scholarship',
    deadline: '2026-09-30',
    location: 'Global',
    stipendOrPrize: 'Fully Funded (Tuition, Stipend, Airfare, Health Insurance)',
    techStackOrEligibility: ['Undergraduate Degree', 'Pakistani Citizen', 'GRE Required', 'All Majors'],
    description: 'The prestigious Fulbright scholarship for Pakistani citizens to pursue Master\'s or PhD degrees at top US universities.',
    applyUrl: 'https://www.usefp.org/scholarships/fulbright.cfm',
    featured: true,
    postedDate: '2026-07-15'
  },
  {
    id: 'opp_003',
    title: 'Remote AI/ML Software Engineering Intern',
    organization: 'Turing.com International',
    category: 'Internship',
    deadline: '2026-08-10',
    location: 'Remote',
    stipendOrPrize: '$1,200 / month',
    techStackOrEligibility: ['Python', 'React', 'TypeScript', 'REST APIs', 'Git'],
    description: '3-month remote internship with US tech startups working on agentic workflows, LLM fine-tuning, and full-stack web development.',
    applyUrl: 'https://www.turing.com/careers/internships',
    featured: true,
    postedDate: '2026-07-18'
  },
  {
    id: 'opp_004',
    title: 'Erasmus Mundus Joint Master Degree (EMJMD) 2026',
    organization: 'European Commission',
    category: 'Scholarship',
    deadline: '2026-10-15',
    location: 'Global',
    stipendOrPrize: '€1,400 / month stipend + Full Tuition Waiver',
    techStackOrEligibility: ['Bachelor\'s Degree', 'English Proficiency', 'Computer Science / Engineering'],
    description: 'Study across 2-3 European countries in top AI, Data Science, and Software Engineering Master\'s programs with full funding.',
    applyUrl: 'https://ec.europa.eu/programmes/erasmus-plus/opportunities/individuals/students/erasmus-mundus-joint-master-degrees_en',
    featured: false,
    postedDate: '2026-07-10'
  },
  {
    id: 'opp_005',
    title: 'Ignite National Technology Fund Student R&D Grant',
    organization: 'Ministry of IT & Telecom Pakistan',
    category: 'Grant',
    deadline: '2026-08-30',
    location: 'Pakistan',
    stipendOrPrize: 'Up to PKR 500,000 Final Year Project Funding',
    techStackOrEligibility: ['Final Year Pakistani Students', 'AI / IoT / Web Projects', 'HEC Recognized University'],
    description: 'Grants for final-year undergraduate students developing innovative software and hardware products solving local national problems.',
    applyUrl: 'https://ignite.org.pk/ngiri/',
    featured: true,
    postedDate: '2026-07-22'
  },
  {
    id: 'opp_006',
    title: 'Devpost Open Source GenAI Challenge',
    organization: 'Devpost & Anthropic',
    category: 'Hackathon',
    deadline: '2026-08-25',
    location: 'Remote',
    stipendOrPrize: '$30,000 Cash + API Credits',
    techStackOrEligibility: ['TypeScript', 'Python', 'LLM Prompt Engineering', 'Open Source'],
    description: 'Create open-source developer tools, CLI agents, or productivity apps using modern LLM APIs.',
    applyUrl: 'https://devpost.com/hackathons/genai-challenge',
    featured: false,
    postedDate: '2026-07-12'
  },
  {
    id: 'opp_007',
    title: 'Remote Full-Stack React & Node.js Fellow',
    organization: 'Major League Hacking (MLH) Fellowship',
    category: 'Internship',
    deadline: '2026-09-05',
    location: 'Remote',
    stipendOrPrize: 'Educational Stipend ($1,000/mo) + Mentorship',
    techStackOrEligibility: ['React', 'Node.js', 'Git', 'Open Source Contributor'],
    description: '12-week remote internship where fellows contribute to major open-source projects under guidance from senior software engineers.',
    applyUrl: 'https://fellowship.mlh.io/',
    featured: false,
    postedDate: '2026-07-16'
  },
  {
    id: 'opp_008',
    title: 'Google Summer of Code (GSoC) 2026 Contributor',
    organization: 'Google Open Source Initiative',
    category: 'Internship',
    deadline: '2026-08-20',
    location: 'Remote',
    stipendOrPrize: '$1,500 - $3,000 Stipend based on PPP',
    techStackOrEligibility: ['Open Source', 'Python / JS / C++', 'Git', 'University Student'],
    description: 'Write code for top global open-source organizations (Mozilla, Python Foundation, TensorFlow) during a structured 12-week program.',
    applyUrl: 'https://summerofcode.withgoogle.com/',
    featured: true,
    postedDate: '2026-07-08'
  },
  {
    id: 'opp_009',
    title: 'Pakistan Tech Summit & Youth AI Exhibition',
    organization: 'PM Youth Programme & NAVTTC',
    category: 'Tech Event',
    deadline: '2026-08-05',
    location: 'Pakistan',
    stipendOrPrize: 'Free Entry + Startup Showcase Booth',
    techStackOrEligibility: ['Pakistani Students', 'Tech Enthusiasts', 'AI Projects'],
    description: 'National summit featuring tech keynotes, startup pitching sessions, and networking with top local software houses.',
    applyUrl: 'https://pmyp.gov.pk/tech-summit-2026',
    featured: false,
    postedDate: '2026-07-21'
  },
  {
    id: 'opp_010',
    title: 'Commonwealth Master\'s Scholarship for Pakistan',
    organization: 'Commonwealth Scholarship Commission UK',
    category: 'Scholarship',
    deadline: '2026-10-30',
    location: 'Global',
    stipendOrPrize: 'Full Tuition + £1,347/month Stipend + Flights',
    techStackOrEligibility: ['Undergraduate Degree', 'Pakistani Resident', 'High Academic Record'],
    description: 'Fully funded Master\'s study in the UK for high-achieving Pakistani graduates with potential to drive sustainable development.',
    applyUrl: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/',
    featured: false,
    postedDate: '2026-07-14'
  }
];
