import { MatchResult, Opportunity, UserProfile, OpportunityCategory } from '../types';
import { getDeadlineStatus } from './dateUtils';
import { DecisionInsights, NextBestAction, PipelineItem, PrioritizedOpportunity } from '../features/insights/types';
const categories: OpportunityCategory[] = ['Hackathon', 'Scholarship', 'Internship', 'Grant', 'Tech Event'];
export function calculateDecisionInsights(opportunities: Opportunity[], matches: Record<string, MatchResult>, savedIds: string[], profile?: UserProfile): DecisionInsights {
  const total = opportunities.length;
  const pipeline: PipelineItem[] = categories.map(category => { const items=opportunities.filter(o=>o.category===category); return { category, count: items.length, savedCount: items.filter(o=>savedIds.includes(o.id)).length, percentage: total ? Math.round(items.length/total*100) : 0 }; });
  const urgency={overdue:0,closingSoon:0,upcoming:0,savedClosingSoon:0};
  const trustDistribution={official:0,approved:0,community:0,needsReview:0}; let scoreSum=0; const scoreBuckets={highFit:0,goodFit:0,moderateFit:0,lowFit:0};
  const highPriorityQueue: PrioritizedOpportunity[]=[];
  opportunities.forEach(opportunity=>{ const deadline=getDeadlineStatus(opportunity.deadline); const score=matches[opportunity.id]?.score ?? 0; scoreSum+=score; if(score>=80)scoreBuckets.highFit++; else if(score>=60)scoreBuckets.goodFit++; else if(score>=40)scoreBuckets.moderateFit++; else scoreBuckets.lowFit++; if(deadline.isExpired)urgency.overdue++; else if(deadline.status==='Closing soon'){urgency.closingSoon++; if(savedIds.includes(opportunity.id))urgency.savedClosingSoon++;} else urgency.upcoming++; if(opportunity.trustTier==='tier-1-official')trustDistribution.official++; else if(opportunity.trustTier==='tier-2-verified-platform')trustDistribution.approved++; else if((opportunity.trustScore??50)<50 || opportunity.verificationState==='needs-review')trustDistribution.needsReview++; else trustDistribution.community++; if(!deadline.isExpired){const priority=Math.min(100,Math.round(score*.45)+(deadline.status==='Closing soon'?25:10)+(savedIds.includes(opportunity.id)?15:0)+(opportunity.trustTier==='tier-1-official'?15:opportunity.trustTier==='tier-2-verified-platform'?10:5)); highPriorityQueue.push({opportunity,matchScore:score,priorityScore:priority,daysRemaining:deadline.daysRemaining,reasons:[score>=75?'Strong profile fit':'Explore fit details',deadline.status==='Closing soon'?'Deadline is near':'Active opportunity',savedIds.includes(opportunity.id)?'Already saved':'' ].filter(Boolean)}); }});
  highPriorityQueue.sort((a,b)=>b.priorityScore-a.priorityScore);
  const actions: NextBestAction[]=[]; const urgent=highPriorityQueue.find(item=>item.matchScore>=75 && item.daysRemaining!==null && item.daysRemaining<=7); if(urgent) actions.push({id:'urgent',type:'urgent_apply',title:`Act on ${urgent.opportunity.title}`,description:'Prepare a tailored application while the deadline is still open.',why:'High match score plus a near deadline.',actionLabel:'Open Copilot',opportunityId:urgent.opportunity.id}); else if(urgency.savedClosingSoon) actions.push({id:'saved',type:'review_saved',title:'Review saved deadlines',description:'A bookmarked opportunity is closing soon.',why:'Saved opportunities are strongest signals of intent.',actionLabel:'Review saved'}); const high=highPriorityQueue.find(item=>item.matchScore>=80&&!savedIds.includes(item.opportunity.id)); if(high) actions.push({id:'save',type:'high_match_save',title:`Save ${high.opportunity.title}`,description:'Keep a high-fit opportunity in your action queue.',why:'Its profile match is at least 80%.',actionLabel:'Save opportunity',opportunityId:high.opportunity.id}); if(!profile?.targetCategories?.length) actions.push({id:'profile',type:'profile_enhancement',title:'Refine your target categories',description:'Add what you want to pursue for sharper recommendations.',why:'Your profile has no target categories yet.',actionLabel:'Edit profile'}); if(total<5) actions.push({id:'ingest',type:'pipeline_ingest',title:'Grow your opportunity pipeline',description:'Add a trusted URL or paste an announcement.',why:'More relevant listings produce better decisions.',actionLabel:'Ingest opportunity'});
  return {pipeline,urgency,matchDistribution:{...scoreBuckets,avgScore:total?Math.round(scoreSum/total):0},trustDistribution,conversion:{totalOpportunities:total,savedCount:savedIds.length,conversionRate:total?Math.round(savedIds.length/total*100):0},highPriorityQueue:highPriorityQueue.slice(0,8),nextBestActions:actions.slice(0,4)};
}
